//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBC_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> WarehouseId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
